<!-- Modal ADD NEW BAYER -->
<div class="modal fade" id="myModalNorm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<!-- Modal Header -->
			<div class="modal-header">
				<button type="button" class="close"
				        data-dismiss="modal">
					<span aria-hidden="true">&times;</span>
					<span class="sr-only">Close</span>
				</button>
				<h4 class="modal-title" id="myModalLabel">
					Добавление нового покупателя
				</h4>
			</div>

			<!-- Modal Body -->
			<div class="modal-body">
				<?= $this->tag->form(["export/add", "class" => "form"]) ?>
				<div class="form-group">
					<?= $this->tag->textField(["addbuyer", "class" => "form-control", "placeholder" => "Имя"]) ?>
				</div>
				<div class="form-group">
					<?= $this->tag->textField(["buyerdescr", "class" => "form-control", "placeholder" => "Описание"]) ?>
				</div>
				<div class="form-group">
					<?= $this->tag->textField(["sales_apikey", "class" => "form-control", "placeholder" => "Api key"]) ?>
				</div>
				<div class="form-group">
					<?= $this->tag->textField(["campaign_id", "class" => "form-control", "placeholder" => "campaign_id", "value" => "0"]) ?>
				</div>
				<div class="form-group">
					<?= $this->tag->textField(["brand", "class" => "form-control", "placeholder" => "brand"]) ?>
				</div>
			</div>

			<!-- Modal Footer -->
			<div class="modal-footer">
				<?= $this->tag->submitButton(["Добавить", "class" => "btn btn-primary", "id" => "addBuyer"]) ?>
				<?= $this->tag->endForm() ?>
			</div>
		</div>
	</div>
</div>