<div class="container-fluid">
    <br>
    <section class="topInputs">
        <div class="row">
            <div class="col-md-2">
                <!-- left block -->
                <h2>Экспорт</h2>
                <br>
                <br>
                <div class="topBlock">
					<?= $this->tag->form(["export", "class" => "form-inline", "method" => "post"]) ?>
                    <label for="exampleInputFile">Экспорт</label>
                    <br>
					<?= $this->tag->submitButton(["Экспортировать", "class" => "btn btn-danger", "id" => "exampleInputFile"]) ?>
					<?= $this->tag->endForm() ?>
                </div>
                <br>
                <hr>
                <div class="botBlock">
					<?= $this->tag->form(["sendAPI", "class" => "form-inline", "method" => "post"]) ?>
                    <label for="sendApi">Передать лиды через API</label>
                    <br>
					<?= $this->tag->submitButton(["Передать", "class" => "btn btn-primary", "id" => "sendApi"]) ?>
					<?= $this->tag->endForm() ?>
                </div>

            </div>

            <!--  center block -->
            <div class="col-md-4 col-md-offset-1">
                <h2>Выбор</h2>
                <br>
                <br>
                <div class="selectWrap">
                    <form class="">

                        <label for="country">Выберите страну</label>
                        <select class="form-control" id="country" multiple>
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                            <option>11</option>
                            <option>12</option>
                            <option>13</option>
                            <option>14</option>
                            <option>15</option>
                        </select>
                        <br>
                        <label for="country">Выберите регион</label>
                        <select class="form-control" id="region">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>


                </div>


                <div class="form-group">
                    <label for="exampleInputName2">Количество</label>
                    <input type="number" class="form-control" id="exampleInputName2" placeholder="100" value="100">
                </div>
                <label for="country">Покупатель</label>
                <select class="form-control" id="buyer">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
                <br>

                <button type="submit" class="btn btn-success">Показать</button>
                </form>
            </div>


            <!--   right block -->
            <div class="col-md-4 col-md-offset-1">
                <h2>Отчет</h2>
                <br>
                <br>
                <br>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <tr>
                            <th>Регион</th>
                            <th>Продано</th>
                            <th>Доступно</th>
                            <th>Всего</th>
                        </tr>
                        <tr>
                            <th>English</th>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>Russian</th>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>German</th>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>NoCall</th>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <th>Total</th>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </table>
                </div>
                <hr>

				<?= $this->tag->form(["addBuyer", "class" => "form-inline", "method" => "post"]) ?>
                <label for="addBuyer">Добавить покупателя</label>
                <br>
				<?= $this->tag->textField(["addBuyer", "class" => "form-control", "placeholder" => "Имя"]) ?>
				<?= $this->tag->textField(["buyerDescr", "class" => "form-control", "placeholder" => "Описание"]) ?>
                <br>
                <br>
				<?= $this->tag->submitButton(["Добавить", "class" => "btn btn-primary", "id" => "addBuyer"]) ?>
				<?= $this->tag->endForm() ?>


            </div>

    </section>
</div>
<br>
<hr>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">

                <table class="table table-bordered table-striped">
                    <tr>
                        <th>LeadID</th>
                        <th>First_name</th>
                        <th>Last_name</th>
                        <th>E-Mail</th>
                        <th>Phone</th>
                        <th>CountryISO</th>
                    </tr>
		            <?php

		            foreach ($res as $arrs) {
			            echo '<tr>';
			            foreach ($arrs as $k => $v) {
				            echo "<td>" . $v . "</td>";
			            }
			            echo '</tr>';
		            }
		            echo '<table>';
		            ?>
            </div>
        </div>
    </div>
</div>