<?= $this->getContent() ?>
<div class="container">
    <div class="row">
        <h2>Импорт</h2>
        <hr>
        <br>
        <div class="col-md-6">
            <div class="text-center">
                <!-- left block -->
                <div class="topBlock">

					<?= $this->tag->form(["invoices/companies", "class" => "form-inline", "method" => "post", "enctype" => "multipart/form-data"]) ?>
                    <select name="sales" class="form-control" id="sales">
						<?php
						foreach ($sellers as $key => $value) {
							echo "<option name='{$value['sellername']}' value='{$value['sellerid']}'>" . $value['sellername'] . '</option>';
						}
						?>
                    </select>
                    <br><br>
                    <input type="file" name="impFile" class="btn btn-success" id="impFile">
                    <br><br>
					<?= $this->tag->submitButton(["Импортировать", "class" => "btn btn-info", "id" => "fileImp"]) ?>
					<?= $this->tag->endForm() ?>
                    <p>Последний импорт был
						<?php
						foreach ($file_import_info as $key => $value) {
							foreach ($value as $k => $v) {
								echo '<div class="text-success" style="font-size: 10px">' . $v . '</div>';
							}
						}
						?>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
			<?= $this->tag->form(["invoices/companies"]) ?>
            <label for="addBuyer">Добавить продавца</label>
            <br>
            <div class="form-group">
				<?= $this->tag->textField(["addsales", "class" => "form-control", "placeholder" => "Имя"]) ?>
            </div>
            <div class="form-group">
				<?= $this->tag->textField(["salesdescr", "class" => "form-control", "placeholder" => "Описание"]) ?>
            </div>

            <br>
			<?= $this->tag->submitButton(["Добавить", "class" => "btn btn-primary", "id" => "addSales"]) ?>
			<?= $this->tag->endForm() ?>
        </div>
    </div>
</div>