<?= $this->getContent() ?>
<div class="container">
    <div class="row">
        <div class="col-md-3 col-xs-6">
            <h3>Экспорт</h3>

			<?= $this->tag->form(["invoices/export"]) ?>
            <div class="form-group">
				<?= $this->tag->textField(["export", "value" => "export", "hidden" => "hidden"]) ?>
            </div>
			<?= $this->tag->submitButton(["Экспортировать", "class" => "btn btn-danger", "id" => "exampleInputFile"]) ?>
			<?= $this->tag->endForm() ?>

            <div class="text-left">Отчет по Экспорту:</div>
			<?php
			foreach ($arr_export as $key => $value) {
				foreach ($value as $k => $v) {
					echo '<div class="text-success text-left" style="font-size: 10px">' . $v . '</div>';
				}
			}
			?>
            <hr>
			<?= $this->tag->form(["invoices/api"]) ?>
			<?= $this->tag->submitButton(["Передать через API", "class" => "btn btn-primary", "id" => "sendApi"]) ?>
			<?= $this->tag->endForm() ?>
        </div>
        <div class="col-md-5 col-xs-6">
            <h3>Выбор</h3>
            <input id="toggle-event" type="checkbox" checked data-toggle="toggle" data-on="Страны" data-off="Регионы"
                   data-onstyle="success" data-offstyle="danger">
            <br><br>
            <div class="selectWrap">
				<?= $this->tag->form(["invoices/index"]) ?>
                <select name="country" class="form-control" id="country">
					<?php
					foreach ($arr_option_country as $key => $value) {
						echo "<option name='{$value['country']}' value='{$value['isocode']}'>" . $value['country'] . '</option>';
					}
					?>
                </select>

                <select name="region" class="form-control" id="region">
					<?php
					foreach ($arr_option_regions as $key => $value) {
						echo "<option name='{$value['region']}' value='{$value['region']}'>" . $value['region'] . '</option>';
					}
					?>
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputName2">Количество</label>
                <input type="number" name="cnt_number" class="form-control" id="exampleInputName2" placeholder="100"
                       value="100">
            </div>
            <label for="buyer">Покупатель</label>
            <select name="buyer" class="form-control" id="buyer">
				<?php
				foreach ($arr_option_buyers as $key => $value) {
					echo "<option name='{$value['buyername']}' value='{$value['buyerid']}'>" . $value['buyername'] . '</option>';
				}
				?>
            </select>
            <br>
			<?= $this->tag->submitButton(["Показать", "class" => "btn btn-primary", "id" => "preview"]) ?>
			<?= $this->tag->endForm() ?>
        </div>
        <div class="col-md-4 col-xs-12">
            <h3>Отчет</h3>
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Регион</th>
                        <th>Продано</th>
                        <th>Доступно</th>
                        <th>Всего</th>
                    </tr>
					<?php
					foreach ($arr_buyers_preview as $arrs) {
						echo '<tr>';
						foreach ($arrs as $k => $v) {
							echo '<td>' . $v . '</td>';
						}
						echo '</tr>';
					}
					?>
                </table>
            </div>
			<?= $this->tag->form(["invoices/index", "class" => "form"]) ?>
            <label for="addBuyer">Добавить покупателя</label>
            <div class="form-group">
				<?= $this->tag->textField(["addbuyer", "class" => "form-control", "placeholder" => "Имя"]) ?>
            </div>
            <div class="form-group">
				<?= $this->tag->textField(["buyerdescr", "class" => "form-control", "placeholder" => "Описание"]) ?>
            </div>
            <div class="form-group">
				<?= $this->tag->textField(["sales_apikey", "class" => "form-control", "placeholder" => "Api key"]) ?>
            </div>
            <div class="form-group">
				<?= $this->tag->textField(["campaign_id", "class" => "form-control", "placeholder" => "campaign_id"]) ?>
            </div>
            <div class="form-group">
				<?= $this->tag->textField(["brand", "class" => "form-control", "placeholder" => "brand"]) ?>
            </div>
			<?= $this->tag->submitButton(["Добавить", "class" => "btn btn-primary", "id" => "addBuyer"]) ?>
			<?= $this->tag->endForm() ?>
        </div>
    </div>

    <div class="row">
        <div class="text-left">
            <span>Покупатель :<b><?= $bayer_id ?></b></span>
            <span>Кол-во :<b><?= $cnt_number ?></b></span>
            <span>Страна  :<b><?= $country ?></b></span>
            <span>Регион  :<b><?= $region ?></b></span>
        </div>
        <hr>
        <div class="col-xs-12">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Lead-ID</th>
                        <th>Имя</th>
                        <th>Код страны</th>
                        <th>Телефон</th>
                        <th>Email</th>
                    </tr>
					<?php
					foreach ($leads as $arrs) {
						echo '<tr>';
						foreach ($arrs as $k => $v) {
							echo "<td>" . $v . "</td>";
						}
						echo '</tr>';
					}
					?>
                </table>
            </div>
        </div>
    </div>
</div>
<div id="scroller"></div>
<style>
    #scroller {
        position: fixed;
        bottom: 0;
        right: 0;
        background: transparent url(../img/icon-scroll-top.png) no-repeat left top;
        width: 128px;
        height: 128px;
        cursor: pointer;
        display: none;
    }
</style>
<script type="text/javascript" src="../js/jquery.min.js"></script>
<div id="console-event"></div>
<script>
    $(document).ready(function () {
        $(window).scroll(function () {
            var scroller = $('#scroller');
            if ($(this).scrollTop() > 0) {
                scroller.fadeIn();
            } else {
                scroller.fadeOut();
            }
        });
        scroller.click(function () {
            $('body,html').animate({
                scrollTop: 0
            }, 400);
            return false;
        });
        var region = $('#region');
        var country = $('#country');
        region.css('display', 'none');
        $('#toggle-event').change(function () {
            var i = $(this).prop('checked');
            if (i == true) {
                country.css('display', 'block');
                region.css('display', 'none');
                region.removeProp('value');
            } else {
                country.css('display', 'none');
                region.css('display', 'block');
                country.removeProp('value');
            }
        })
    });
</script>