<?= $this->getContent() ?>
<h2>Изменить данные аккаунта</h2>
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="profile left">
				<?= $this->tag->form("invoices/profile") ?>
                <div class="clearfix">
                    <label for="name">Полное имя:</label>
                    <div class="input">
						<?= $this->tag->textField(["name", "class" => "form-control"]) ?>
                    </div>
                </div>
                <br>
                <div class="clearfix">
                    <label for="email">Email:</label>
                    <div class="input">
						<?= $this->tag->textField(["email", "class" => "form-control"]) ?>
                    </div>
                </div>
                <br>
                <div class="clearfix">
                    <input type="button" value="Обновить" class="btn btn-primary btn-large btn-info"
                           onclick="Profile.validate()">
                    &nbsp;<?= $this->tag->linkTo("invoices/index", "Отмена") ?>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>