<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".collapse">
            <span class="sr-only">Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">LeadPro</a>
    </div>
    <div class="container">
		<?php
		$elements = new Elements();
		echo $elements->getMenu();
		?>
    </div>
</nav>
<?= $this->getContent() ?>

<div id="scroller"></div>
<hr>
<div class="container">
    <div class="row">
        <div class="col-md-6">
			<?php
			$date = new DateTime();
			echo "<p>LeadPro &copy; " . $date->format('d-m-Y') . "</p>";
			?>
        </div>
        <div class="col-md-6">

        </div>
    </div>
</div>




